import type { CanvasRenderer } from './CanvasRenderer';
import type { ActPressureDebugState } from '../game/ActPressure';
import type { EnemyRolePressureSummary } from '../game/EnemyRolePressure';
import type { EnvironmentStressDebugState } from '../game/EnvironmentStress';
import type { ItemLoadoutStressModel } from '../game/ItemStress';
import type { SecondActFinaleDebugState } from '../game/SecondActFinale';
import type { InputAction } from '../systems/InputSystem';
import type { ContractThemeDebugState } from '../ui/ContractTheme';
import type { MissionDebugState } from '../game/MissionDirector';
import type { ShipLoadoutDebugState } from '../game/ShipLoadout';
import type { EngineeringDebugState } from '../game/Foundry';
import type { FactionCampaignDebugState } from '../game/FactionCampaign';
import type { RunTimelineDebugState } from '../game/RunTimeline';
import type { CarrierDebugState } from '../game/CarrierCommand';
import type { FactionFrontDebugState } from '../game/FactionFront';
import type { CrewArcDebugState } from '../game/CrewArc';
import type { FleetDebugState } from '../game/Fleetcraft';
import type { ApexDebugState } from '../game/ApexHunt';

export interface SceneDebugState {
  readonly seed: string;
  readonly entityCount: number;
  readonly entityCounts?: {
    readonly total: number;
    readonly player: number;
    readonly enemies: number;
    readonly allies?: number;
    readonly boss: number;
    readonly projectiles: number;
    readonly playerProjectiles: number;
    readonly enemyProjectiles: number;
    readonly allyProjectiles?: number;
    readonly pickups: number;
    readonly looseCurrencyPickups: number;
    readonly looseCurrencyValue: number;
    readonly looseCurrencyCredits: number;
    readonly looseCurrencySalvage: number;
    readonly looseCurrencyPickupCap: number;
    readonly looseCurrencyValueCap: number;
    readonly effects: number;
    readonly pickupsAndEffects: number;
    readonly telegraphs: number;
    readonly environmentObjects: number;
    readonly destructibles: number;
    readonly obstacles: number;
    readonly proximityMines?: number;
    readonly armedProximityMines?: number;
    readonly setPieceComponents?: number;
    readonly setPieceTargets?: number;
    readonly setPieceProjectiles?: number;
    readonly setPieceProjectileCap?: number;
  };
  readonly distance?: number;
  readonly sectorLength?: number;
  readonly scrollSpeed?: number;
  readonly exitSequence?: string;
  readonly sectorCooldown?: string;
  readonly destructionSequence?: string;
  readonly arenaPhase?: string;
  readonly debugScenario?: string;
  readonly inputMode?: string;
  readonly hudMode?: string;
  readonly contractTheme?: ContractThemeDebugState;
  readonly shipLoadout?: ShipLoadoutDebugState;
  readonly engineering?: EngineeringDebugState;
  readonly combinedProc?: {
    readonly budget: number;
    readonly totalApplied: number;
    readonly totalSkipped: number;
    readonly peakHook: string | null;
    readonly peakApplications: number;
    readonly lastOrder: readonly string[];
  };
  readonly mission?: MissionDebugState;
  readonly items?: ItemLoadoutStressModel;
  readonly enemyRoles?: EnemyRolePressureSummary;
  readonly environmentStress?: EnvironmentStressDebugState;
  readonly setPiece?: {
    readonly active: boolean;
    readonly name: string;
    readonly stageLabel: string;
    readonly beat: string;
    readonly targetLabel: string;
    readonly destroyedComponents: number;
    readonly totalComponents: number;
    readonly objectiveTargetsDestroyed: number;
    readonly objectiveTargetsTotal: number;
    readonly layoutLabel: string;
    readonly safeLaneLabel: string;
    readonly bossLockActive: boolean;
  };
  readonly factionCampaign?: FactionCampaignDebugState;
  readonly crew?: {
    readonly activeCommand: string;
    readonly commandCooldown: number;
    readonly issuedCommands: number;
    readonly allies: readonly string[];
  };
  readonly runTimeline?: RunTimelineDebugState;
  readonly carrier?: CarrierDebugState;
  readonly boarding?: {
    readonly operationId: string;
    readonly title: string;
    readonly target: string;
    readonly rooms: number;
    readonly doors: number;
    readonly hazards: number;
    readonly loot: number;
    readonly extractionSeconds: number | null;
    readonly integrations: readonly string[];
    readonly environmentKind: string;
    readonly environmentLabel: string;
  };
  readonly factionFronts?: FactionFrontDebugState;
  readonly crewArcs?: CrewArcDebugState;
  readonly fleet?: FleetDebugState;
  readonly apex?: ApexDebugState;
  readonly scenarioLab?: {
    readonly scenarioCount: number;
    readonly activeScenario: string | null;
    readonly systems: readonly string[];
    readonly budget: string;
  };
  readonly actPressure?: ActPressureDebugState;
  readonly finale?: SecondActFinaleDebugState;
  readonly upgradeEffects?: readonly string[];
  readonly act?: {
    readonly id: string;
    readonly name: string;
    readonly shortLabel: string;
    readonly index: number;
    readonly sectorIndex: number;
    readonly sectorCount: number;
    readonly rewardTier: string;
    readonly pressureTier: string;
    readonly bossGate: string;
    readonly transition: string;
  };
  readonly interAct?: {
    readonly targetAct: string;
    readonly choices: readonly string[];
    readonly applied: string | null;
  };
  readonly progression?: {
    readonly salvageBank?: number;
    readonly purchasedUpgrades?: number;
    readonly totalUpgrades?: number;
    readonly availableUpgrades?: number;
    readonly runCredits?: number;
    readonly runSalvage?: number;
  };
  readonly sector?: {
    readonly index: number;
    readonly id: string;
    readonly name: string;
    readonly backgroundId?: string;
    readonly encounterPacing?: string;
    readonly pacing?: string;
    readonly pacingBeat?: string;
    readonly objective?: string;
    readonly objectiveState?: string;
    readonly routeTags?: string;
    readonly hazardZones?: string;
    readonly hazardRuntime?: string;
  };
  readonly backgroundPrimitives?: number;
  readonly backgroundLayers?: number;
  readonly activeLandmarks?: number;
  readonly activeHazards?: number;
  readonly viewport?: {
    readonly width: number;
    readonly height: number;
    readonly className: string;
    readonly dpr: number;
    readonly scale: number;
    readonly canvasPixelWidth: number;
    readonly canvasPixelHeight: number;
    readonly safeFrameX: number;
    readonly safeFrameY: number;
    readonly safeFrameWidth: number;
    readonly safeFrameHeight: number;
    readonly arenaWidth?: number;
    readonly arenaHeight?: number;
  };
}

export interface Scene {
  readonly id: string;
  enter?(params?: unknown): void;
  exit?(): void;
  update(dt: number): void;
  render(renderer: CanvasRenderer, alpha: number): void;
  handleAction?(action: InputAction): void;
  getDebugState?(): SceneDebugState;
}
